name: CI

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  test_js:
    name: Node.js v${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 17]
    steps:
      - uses: actions/checkout@main

      - name: (env) setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.14.2

      - name: (env) setup node v${{ matrix.node }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
          check-latest: true

      - name: Install
        run: pnpm install

      - name: Compiles
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Check Types
        run: pnpm typecheck

  test_rs:
    name: Rust ${{ matrix.rustv }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rustv: [nightly, stable]
    steps:
      - uses: actions/checkout@main

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rustv }}

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Lint
        run: cargo fmt --all -- --check

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
